language: ruby

rvm:
  - "2.7"
  - "2.6"
  - "2.5"

cache: bundler

# 2020-04-24: Avoid deprecation warning about --deployment and --path flags
install: bundle install --jobs=3 --retry=3
env:
  global:
    - BUNDLE_PATH=vendor/bundle
